### ISSUE TITLE
International Day Event

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/Lahore#3]
@usmantahirr Pinging in regards to your mail and the event issue: https://github.com/nodeschool/international-day/issues/22

**Comment by iancrowther** [comment]
is this event still taking place?

**Comment by iancrowther** [comment]
do you have photos/videos/logos formthe event?

**Comment by usmantahirr** [comment]
This event happened but it wasn't of that scale. I can find some pictures but they weren't impressive, this was only reason I was silent about it. I am planning International day for 2016 of a bigger scale.

In 2015 Budget was a big issue and I was unable to rise enough funding. I've talked to people to be ready for 2016's budget and fundings. I am preparing proposals now a days

**Comment by iancrowther** [comment]
@usmantahirr - even if it was just you, Lahore was involved and will be included :-)

Send me a lahore hex logo, the photo and your in.. the quality is irrelivant

**Comment by usmantahirr** [comment]
Great, let me find some, I'll send you.
