### ISSUE TITLE
World Node Day NodeSchool Lahore

### ISSUE THREAD

**Issue by abdulhannanali** [nodeschool/Lahore#4]
We are planning a NodeSchool Lahore event on 21st May, 2016. It's never too late to organize an awesome event like this. Let's talk and code nodeJS on this day in Lahore, Pakistan and show some Lahore in the NodeSchool House. The event is open for beginners and experts a like. You can register as a mentor as well as an attendee. Every thing we have to do is to be done real quick because there's not much time left. 
You can register as a mentor as well as an attendee. Mentor should have preferably some experience with coding and preferably in Node.JS too.. Thank you for your interest. Looking forward for your contribution to the NodeSchool Event.

UPDATE 1: Fill out the form by clicking [here](https://docs.google.com/forms/d/1mMgmfwV3qYcCYOz-0Alihu3mLp2JhbuutkyYZprFx1Q/viewform?c=0&w=1) if you are willing to attend this event.

**Comment by saifali96** [comment]
Registered, hoping for a great event.

**Comment by abdulhannanali** [comment]
Thanks @saifali96 Looking forward to have you. That's great
