### ISSUE TITLE
Is this chapter still working?

### ISSUE THREAD

**Issue by WaleedAshraf** [nodeschool/Lahore#6]
Hi,

@sheharyarn @usmantahirr 
Are you guys still running this? 

If not, I want to take over NodeSchool Lahore Chapter.
I have been working on Nodejs for more than 2 years. And now trying to contribute to project as much as I can. I have some space available at the current office which can be used for talks/sessions. 

Any suggestions/feedback about it?
Also, let me know if anyone of you thinks we can have a meeting?

**Comment by usmantahirr** [comment]
Hi Waleed, I am working on its website. I am planning to revamp it on this international day ie. 22 May.
You're free to join us, we always need more and more help. We can work together on this one.

Contact me whenever you come back from US and we can meet somewhere over the coffee to plan something out

**Comment by WaleedAshraf** [comment]
@usmantahirr thanks for your time yesterday. Looking forward to bring more to this chapter. 🎉 
Closing this issue.
